name: Testing
on: push

jobs:
    test_frontend:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [10.x, 12.x, 14.x, 15.x]

        steps:
			-	uses: actions/checkout@v2
			-	uses: actions/setup-node@v3
			-	working-directory: ./frontend_react
            - 	name: Use Node.js ${{ matrix.node-version }}
				with:
					node-version: ${{ matrix.node-version }}
            - 	run: |
					npm ci
					npm run build --if-present
					npm test
